# Generated by Django 6.0.6 on 2026-07-04 07:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('4.0'), max_digits=2),
        ),
    ]
