# Generated by Django 6.0.6 on 2026-07-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_otp_customuser_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('seeker', 'Job Seeker'), ('employer', 'Employer / Company')], default='seeker', max_length=20),
        ),
    ]
